branch-defaults:
  main:
    environment: raasystem-backend-env
global:
  application_name: raasystem-backend
  branch: null
  default_ec2_keyname: raasystem-rotated
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
